---
toc: true
format: 
  html: 
    sidebar: true
    anchor-sections: true
---

# Pollination Ecology Group {#about style="text-align: center;"}

Pollination Ecology Group is a research group based in Prague at the Faculty of Science, Charles University. Our main goal is to investigate plant-pollinator interactions. We are interested in how these interactions shape plant and pollinator communities, how they are affected by environmental changes, and how they can be managed for conservation purposes.

## Topics

#### Long-term study of plant-pollinator system

Our group is carring out a long-term study of plant-pollinator system in Central Bohemia region, near to village Vernýřov. We focused not only on relations between plants and pollinators, but also on spatial and temporal variability in plant-pollinator
interactions of a grassy meadow. Moreover, deep knowledge of the system allows to us focus more on looking for answers on more delicate questions in pollination ecology. 	

## People

Jiří Hadrava

## Publications

## Join us!

## Contacts
